name: "Azure Infra"
on:
  push:
    branches:
      - main
jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v3  
      - name: setup Terraform  
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      # - name: Setup Azure CLI
      #   uses: azure/login@v1
      - name: Create Public Key file
        run: |
          echo ${{ vars.AZ_PUB_KEY }} > /tmp/id_az.pub
          cat /tmp/id_az.pub

      - name: Initialize Terraform
        run: |
          terraform -chdir=azure_infra init -var SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Terraform plan
        run: |
          terraform -chdir=azure_infra plan
      - name: Terraform apply
        run: |
          terraform -chdir=azure_infra destroy -auto-approve


