name: "Azure Infra"
on:
  workflow_dispatch:
    inputs:
      Action: 
        description: Whehter to create or delete
        required: true
        default: Apply
        type: choice
        options:
          - Apply
          - Destroy
  push:
    branches:
      - main
jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      Action: Applys
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v3  
      - name: setup Terraform  
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      # - name: Setup Azure CLI
      #   uses: azure/login@v1
      - name: Create Public Key file
        run: | 
          echo ${{ vars.AZ_PUB_KEY }} > /tmp/id_az.pub
          cat /tmp/id_az.pub
      - name: Initialize Terraform
        run: |
          terraform -chdir=azure_infra init
      - name: Terraform plan
        run: |
          terraform -chdir=azure_infra plan
      - name: Terraform apply
        if: ${{ github.event.inputs.Action == 'Apply' || env.Action == 'Apply' }}
        run: |
          echo "Apply will run"
          # terraform -chdir=azure_infra apply -auto-approve
      - name: Terraform Destroy
        if: ${{ github.event.inputs.Action == 'Destroy' || env.Action == 'Destroy' }}
        run: |
          echo "Destroy will run"
          # terraform -chdir=azure_infra destroy -auto-approve



