name: "Azure Infra"
on:
  push:
    branches:
      - main

env:
  TF_VAR_ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  TF_VAR_ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  
jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v3  
      - name: setup Terraform  
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      # - name: Setup Azure CLI
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Public Key file
        run: |
          echo ${{ secrets.AZ_PUB_KEY }} > /tmp/id_az.pub

      - name: Initialize Terraform
        run: |
          terraform -chdir=azure_infra init 
      - name: Terraform plan
        run: |
          terraform -chdir=azure_infra plan
      - name: Terraform apply
        run: |
          terraform -chdir=azure_infra apply    


