name: "Simple Workflow"
on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v3  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Run my script
        run: python src/hi.py

